name: Type Check and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - run: pip install mypy strip-hints
    - run: mypy --strict rpmdag.py
    - run: strip-hints rpmdag.py -o rpmdag_stripped.py
    - uses: softprops/action-gh-release@v1
      with:
        files: rpmdag_stripped.py
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
